# Generated by Django 5.2.6 on 2025-10-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0005_remove_humedal_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del socio')),
                ('humedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.humedal')),
            ],
        ),
    ]
